#!/bin/sh

find queuejob -name \*.pyc -type f -delete
find queuejob -name \*.pyo -type f -delete
find queuejob -name __pycache__ -type d -delete

find tests -mindepth 2 -type f -delete
find tests -mindepth 2 -type l -delete
find tests -mindepth 1 -type d -delete

rm -rf bin
rm -rf etc
rm -rf build
rm -rf queuejob.egg-info
