#!/bin/sh

find job2q -name \*.pyc -type f -delete
find job2q -name \*.pyo -type f -delete
find job2q -name __pycache__ -type d -delete

find tests -mindepth 2 -type f -delete
find tests -mindepth 2 -type l -delete
find tests -mindepth 1 -type d -delete

rm -r build
rm -r job2q.egg-info
