#!/bin/sh
find enqueuer -name \*.pyc -type f -delete
find enqueuer -name \*.pyo -type f -delete
find enqueuer -name __pycache__ -type d -delete
find tests -mindepth 2 -type f -delete
find tests -mindepth 1 -type d -delete
