#!/usr/bin/env python
import sys
assert sys.version_info >= (2, 6)

from os.path import abspath
from job2q.main import setup
from job2q.utils import makedirs

cfgdir = abspath('./etc')
bindir = abspath('./bin')
makedirs(cfgdir, bindir)
setup(cfgdir=cfgdir, bindir=bindir)

