#!/usr/bin/env python3
import sys
assert sys.version_info >= (3, 6)
from jobq import console_scripts
try:
    console_scripts.config()
except KeyboardInterrupt:
    print('Interrumpido por el usuario')
