#!/bin/bash

delete () {
    read -sn 1 -p "${yellow}No hay archivos nuevos que sincronizar ¿$1 (s/n)?: ${normal}" answer
    echo
    case "$answer" in
      s|y)
        echo -e "${yellow}Los siguientes archivos serán borrados de $host:${normal}\n$(echo "$2" | rsync -ntii --files-from=- --remove-source-files "$host":"\$JOBSHARE/$USER@$HOSTNAME/" "$HOME" | sed -n 's,^.f          ,,p')" | more
        while true; do
            read -p "${yellow}Escriba \"ok\" para proceder o presione ENTER para cancelar: ${normal}" answer
            case "$answer" in
              ok|OK)
                echo -n ${yellow}Borrando los archivos sincronizados... ${normal}
                echo "$2" | rsync -tv --files-from=- --remove-source-files "$host":"\$JOBSHARE/$USER@$HOSTNAME/" "$HOME" | sed -n 's,^.f          ,,p'
                echo Hecho
                echo
                break;;
              ?*) echo Escriba \"ok\" si desea borrar los archivos;;
              *) break;;
            esac
        done;;
      *) :;;
    esac
}

options=$(getopt -n "$0" -o '' -l force,exclude: -- "$@") || exit

eval "set -- $options"

while (( $# )); do
  case "$1" in
    --force) force=; shift;;
    --exclude) expat=$2; shift 2;;
    --) shift; break;;
     *) echo Unknown option: $1; exit 1
  esac
done

if [[ -n $1 ]]; then
    host=$1
else
    echo 'Error: Debe especificar un servidor'
    exit
fi

including=$(rsync -rntii --exclude='.*' ${expat:+--exclude="$expat"} "$host":"\$JOBSHARE/$USER@$HOSTNAME/" "$HOME")
excluding=$(rsync -rntii ${expat:+--include="$expat"} --include='*/' --exclude='*' "$host":"\$JOBSHARE/$USER@$HOSTNAME/" "$HOME")
synced=$(echo "$including$excluding" | sed -n 's,^.f          ,,p')
unsynced=$(echo "$including" | sed -n 's,^>f+++++++++ ,,p')
excluded=$(echo "$excluding" | sed -n 's,^>f+++++++++ ,,p')
conflicting=$(echo "$including" | grep -v '^>f          ' | grep -v '^>f+++++++++ ' | sed -n 's,^>f......... ,,p')

#echo "$including"
#echo "$synced"
#echo "$unsynced"
#echo "$excluded"
#echo "$conflicting"
#exit

if [[ -n $unsynced || -n $conflicting ]]; then
    if [[ -n $unsynced ]]; then
        echo ${yellow}Sincronizando archivos nuevos...${normal}
        echo "$unsynced" | rsync -ztvh --partial-dir=.rsynctmp --progress --files-from=- "$host":"\$JOBSHARE/$USER@$HOSTNAME/" "$HOME"
        echo
    fi
    if [[ -n $conflicting ]]; then
        if [[ -z ${force+?} ]]; then
            echo "${yellow}La versión remota de los siguientes archivos difiere de la versión local:${normal}"
            echo "$conflicting"
            echo "${yellow}Ejecute este escript con la opción --force para sobreescribir las versiones locales${normal}"
        else
            echo ${yellow}Sobreescribiendo los archivos conflictivos...${normal}
            echo "$conflicting" | rsync -ztvh --partial-dir=.rsynctmp --progress --files-from=- "$host":"\$JOBSHARE/$USER@$HOSTNAME/" "$HOME"
        fi
    fi
elif [[ -n $synced ]]; then
    delete "desea borrar los archivos redundantes" "$synced"
elif [[ -n $excluded ]]; then
    delete "desea borrar los archivos excluidos de $host" "$synced"
else
    echo ${yellow}No hay archivos nuevos que sincronizar${normal}
fi

