#!/bin/sh
'exec' 'env' \
"LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{pyldpath}" \
"PYTHONPATH={modulepath}" \
"SPECPATH={specpath}" \
'{python}' "$0" "$@"

from enqueuer.jobinit import drytest, remotehost, files
from enqueuer.jobexec import wait, setup, connect, upload, dryrun, localrun, remoterun

if drytest:
    while files:
        dryrun()
elif remotehost:
    connect()
    while files:
        upload()
    remoterun()
else:
    setup()
    localrun()
    while files:
        wait()
        localrun()

